import type { Metadata } from 'next';
import Footer from '@/components/layout/footer';
import Header from '@/components/layout/header';
import localFont from 'next/font/local';
import './globals.css';

// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   variable: '--font-geist-sans',
//   weight: '100 900',
// });
// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff',
//   variable: '--font-geist-mono',
//   weight: '100 900',
// });

const drukBold = localFont({
  src: './fonts/Druk-Bold.otf',
  variable: '--font-druk-bold',
  weight: '900',
  display: 'swap',
  fallback: ['Arial Black', 'Impact', 'system-ui', 'sans-serif'],
});
const manropeMedium = localFont({
  src: './fonts/Manrope-Medium.ttf',
  variable: '--font-manrope-medium',
  weight: '500',
  display: 'swap',
  fallback: ['Helvetica', 'Arial', 'system-ui', 'sans-serif'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  other: {
    link: [
      {
        rel: 'preload',
        href: '/fonts/Druk-Bold.otf',
        as: 'font',
        type: 'font/otf',
        crossOrigin: 'anonymous',
      },
      {
        rel: 'preload',
        href: '/fonts/Manrope-Medium.ttf',
        as: 'font',
        type: 'font/ttf',
        crossOrigin: 'anonymous',
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${drukBold.variable} ${manropeMedium.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
