import type { Metadata } from 'next';
import Footer from '@/components/layout/footer';
import Header from '@/components/layout/header';
import localFont from 'next/font/local';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
  openGraph: {
    title: 'Create Next App',
    description: 'Generated by create next app',
    url: 'https://yoursite.com',
    siteName: 'Your Site Name',
    locale: 'en_US',
    type: 'website',
  },
};

const drukBold = localFont({
  src: './fonts/Druk-Bold.otf',
  variable: '--font-druk-bold',
  weight: '900',
  display: 'swap',
  fallback: ['Arial Black', 'Impact', 'system-ui', 'sans-serif'],
});
const manropeMedium = localFont({
  src: './fonts/Manrope-Medium.ttf',
  variable: '--font-manrope-medium',
  weight: '500',
  display: 'swap',
  fallback: ['Helvetica', 'Arial', 'system-ui', 'sans-serif'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${drukBold.variable} ${manropeMedium.variable} no-scrollbar antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
